### ISSUE TITLE
Needed a fi_FI folder

### ISSUE THREAD

**Issue by talamus** [MikaVainio/AffinityPublisherFISpelling#6]
I needed to create a `fi_FI` folder inside the `C:\ProgramData\Affinity\Common\1.0\Dictionaries` to get the spell checking to work in Windows 10 Pro.

Perhaps this could be mentioned in the installation instructions.

The instructions that I followed:
https://forum.affinity.serif.com/index.php?/topic/98911-how-do-i-add-additional-dictionaries-to-affinity-publisher/

**Comment by MikaVainio** [comment]
Tools are intended to be used with Affinity Publisher version 2, thus they work with older versions and other applications as well. There were instructions in the README.md file for version 2 only. Unfortunately I don't have anymore version 1 applications installed so I didn't make any installation instructions for previous version. It may require some additional steps to install it properly to the old version. I will add your comments to the README file for Windows users. I suppose that Mac instructions are valid for version 1 also. I added a tip section to the README containing your instructions.

Thanks for sending this issue
